// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')
const fs = require('fs')

describe('Negative number addition', function() {
  this.timeout(30000)
  let driver
  let vars

  if (!fs.existsSync('./screenshots')) {

    fs.mkdirSync('./screenshots');

}
  beforeEach(async function() {

    const chrome = require('selenium-webdriver/chrome');

        const options = new chrome.Options();

        options.addArguments('--headless', '--no-sandbox', '--disable-dev-shm-usage');

        driver = await new Builder().forBrowser('chrome').setChromeOptions(options).build();

    

    

    vars = {}

  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Negative number addition', async function() {
    await driver.get("http://127.0.0.1:8000/")
    await driver.manage().window().setRect({ width: 813, height: 912 })
    await driver.findElement(By.id("num1")).click()
    await driver.findElement(By.id("num1")).sendKeys("-5")
    await driver.findElement(By.id("num2")).sendKeys("5")
    await driver.findElement(By.css("button:nth-child(1)")).click()
    await driver.findElement(By.css("button:nth-child(2)")).click()
    const filename = 'negativenumberaddition';

    const encodedString = await driver.takeScreenshot();

    await fs.writeFileSync(`./screenshots/${filename}.png`,

        encodedString, 'base64');
  })
})
