// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('sub_decimal_integer', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('sub_decimal_integer', async function() {
    await driver.get("http://127.0.0.1:5500/src/index.html")
    await driver.manage().window().setRect({ width: 784, height: 912 })
    await driver.findElement(By.id("num1")).click()
    await driver.findElement(By.id("num1")).sendKeys("5.9")
    await driver.findElement(By.id("num2")).sendKeys("3")
    await driver.findElement(By.css("button:nth-child(2)")).click()
    await driver.findElement(By.css("button:nth-child(3)")).click()
  })
})
