name: Java CI

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    - name: Set up node 20 
      uses: actions/setup-node@v4
      with:
        node-version: '20'
    - name: Grant execute permissions to mvnw
      run: chmod +x src/backend/mvnw
    - name: Build and Run Backend
      run: |
          cd src/backend
          ./mvnw clean spring-boot:run & 
          echo "Waiting for the server to start..."
          attempt_counter=0
          max_attempts=20  # Increased attempts
          sleep_duration=10  # Increased sleep duration
          until $(curl --output /dev/null --silent --head --fail http://localhost:9090/add?num1=5&num2=3); do
              if [ ${attempt_counter} -eq ${max_attempts} ]; then
                echo "Max attempts reached. Server did not start."
                exit 1
              fi
              printf '.'
              attempt_counter=$(($attempt_counter+1))
              sleep ${sleep_duration}
          done
          echo "Server is ready for testing."
    - name: Install Newman
      run: npm install -g newman
    - name: Run Newman Tests
      run: |
          newman run src/backend/src/main/resources/SoftwareQuality.postman_collection.json